-- 코드를 입력하세요
SELECT 
    T3.AUTHOR_ID,
    T3.AUTHOR_NAME,
    T2.CATEGORY,
    SUM(T1.SALES*T2.PRICE) AS TOTAL_SALES
FROM BOOK_SALES T1
     INNER JOIN BOOK T2 ON T1.BOOK_ID = T2.BOOK_ID
     INNER JOIN AUTHOR T3 ON T2.AUTHOR_ID = T3.AUTHOR_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY T3.AUTHOR_ID, T2.CATEGORY
ORDER BY T3.AUTHOR_ID ASC, T2.CATEGORY DESC