-- 코드를 입력하세요
SELECT T1.CART_ID
    FROM CART_PRODUCTS T1
        INNER JOIN CART_PRODUCTS T2 ON T1.CART_ID = T2.CART_ID AND T1.ID <> T2.ID
WHERE T1.NAME = 'MILK' AND T2.NAME = 'YOGURT'
GROUP BY T1.CART_ID