-- 코드를 입력하세요
SELECT T1.PRODUCT_CODE, T1.PRICE * SUM(T2.SALES_AMOUNT) AS SALES FROM PRODUCT T1
INNER JOIN OFFLINE_SALE T2
    ON T1.PRODUCT_ID = T2.PRODUCT_ID
GROUP BY T1.PRODUCT_CODE
ORDER BY T1.PRICE * SUM(T2.SALES_AMOUNT) DESC, T1.PRODUCT_CODE 


# SELECT * FROM OFFLINE_SALE WHERE product_id = 9
