SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT
FROM (SELECT ONLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE, USER_ID
     FROM ONLINE_SALE
     UNION ALL
     SELECT *, NULL AS USER_ID
     FROM OFFLINE_SALE) AS TOTAL_SALE
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID