-- 코드를 입력하세요
SELECT YEAR(T2.SALES_DATE), MONTH(T2.SALES_DATE), GENDER, COUNT(DISTINCT T1.USER_ID) AS USERS
FROM USER_INFO T1
    INNER JOIN ONLINE_SALE T2 ON T1.USER_ID = T2.USER_ID  
WHERE T1.GENDER IS NOT NULL
GROUP BY YEAR(T2.SALES_DATE), MONTH(T2.SALES_DATE), T1.GENDER
ORDER BY YEAR(T2.SALES_DATE), MONTH(T2.SALES_DATE), T1.GENDER