-- 코드를 입력하세요
SELECT T1.ANIMAL_ID, T1.NAME FROM ANIMAL_OUTS T1
    LEFT JOIN ANIMAL_INS T2
        ON T1.ANIMAL_ID = T2.ANIMAL_ID 
WHERE T2.ANIMAL_ID IS NULL
ORDER BY T1.ANIMAL_ID
# SELECT * FROM ANIMAL_INS