-- 코드를 입력하세요
WITH COUNT_USER AS (
    SELECT COUNT(*) AS ALL_USER FROM USER_INFO WHERE JOINED LIKE '2021%'
)
SELECT 
    YEAR(T2.SALES_DATE) AS YEAR, 
    MONTH(T2.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT T1.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT T1.USER_ID)/T3.ALL_USER,1) AS PURCHASED_RATIO
FROM USER_INFO T1
    INNER JOIN ONLINE_SALE T2 ON T1.USER_ID = T2.USER_ID
    JOIN COUNT_USER T3
WHERE JOINED LIKE '2021%'
GROUP BY YEAR(T2.SALES_DATE), MONTH(T2.SALES_DATE)
ORDER BY YEAR(T2.SALES_DATE), MONTH(T2.SALES_DATE)