SELECT O.PRODUCT_ID, P.PRODUCT_NAME, 
    SUM(O.AMOUNT)*P.PRICE AS TOTAL_SALES
FROM FOOD_ORDER O, FOOD_PRODUCT P
WHERE O.PRODUCT_ID = P.PRODUCT_ID
    AND O.PRODUCE_DATE LIKE "2022-05%"
GROUP BY 1
ORDER BY 3 DESC, 1