-- 코드를 입력하세요
SELECT T1.APNT_NO
    , T2.PT_NAME
    , T2.PT_NO
    , T3.MCDP_CD
    , T3.DR_NAME
    , T1.APNT_YMD
FROM APPOINTMENT T1
    INNER JOIN PATIENT T2 ON T1.PT_NO = T2.PT_NO
    INNER JOIN DOCTOR T3 ON T1.MDDR_ID = T3.DR_ID
WHERE (T1.MCDP_CD = 'CS' AND DATE(T1.APNT_YMD) = '2022-04-13' AND T1.APNT_CNCL_YN = 'N')
ORDER BY T1.APNT_YMD