-- 코드를 입력하세요

WITH RECURSIVE CTE AS (
SELECT 0 AS HOUR
    
UNION ALL
    
SELECT HOUR + 1 
    FROM CTE WHERE HOUR < 23
)

SELECT CTE.HOUR, COUNT(AO.ANIMAL_ID) FROM CTE
LEFT JOIN  ANIMAL_OUTS AO ON CTE.HOUR = HOUR(AO.DATETIME)
GROUP BY CTE.HOUR
ORDER BY CTE.HOUR