-- 코드를 입력하세요
SELECT T1.MEMBER_NAME, T2.REVIEW_TEXT, SUBSTRING(T2.REVIEW_DATE,1,10)
FROM MEMBER_PROFILE T1
    INNER JOIN REST_REVIEW T2 ON T1.MEMBER_ID = T2.MEMBER_ID
WHERE T1.MEMBER_ID = 
(SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT