-- 코드를 입력하세요
SELECT 
SUBSTR(T1.PRODUCT_CODE,1,2) AS CATEGORY
, COUNT(SUBSTR(T1.PRODUCT_ID,1,2)) AS PRODUCTS
FROM PRODUCT T1
GROUP BY CATEGORY ORDER BY CATEGORY

# SELECT * FROM PRODUCT ORDER BY PRODUCT_CODE;