-- 코드를 입력하세요
SELECT T1.FLAVOR FROM FIRST_HALF T1
    INNER JOIN ICECREAM_INFO T2 
        ON T1.FLAVOR = T2.FLAVOR AND T2.INGREDIENT_TYPE = 'fruit_based' 
WHERE T1.TOTAL_ORDER > 3000
ORDER BY T1.TOTAL_ORDER DESC