-- 코드를 입력하세요
SELECT T1.CAR_ID FROM CAR_RENTAL_COMPANY_CAR T1
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY T2
    ON T1.CAR_ID = T2.CAR_ID AND MONTH(START_DATE) = 10
WHERE T1.CAR_TYPE = '세단'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC

