-- 코드를 입력하세요
SELECT T1.CATEGORY, SUM(T2.SALES) AS TOTAL_SALES
FROM BOOK T1
    INNER JOIN BOOK_SALES T2
        ON T1.BOOK_ID = T2.BOOK_ID
WHERE 
    YEAR(T2.SALES_DATE) = 2022
    AND MONTH(T2.SALES_DATE) = 1
GROUP BY
    T1.CATEGORY
ORDER BY
    T1.CATEGORY